# Generated by Django 4.2.4 on 2023-08-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miLibreria', '0003_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroCli',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id_trabj',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
