# Generated by Django 4.2.4 on 2023-08-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miLibreria', '0004_remove_cliente_id_remove_trabajador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
